$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://maytetoscano.github.io/bblocks-bioclima/bblock/ogc.bioclima.provenance.indicator-provenance/schema.yaml"
title: "Indicator Provenance"
allOf:
  - $ref: "../ebv-provenance/schema.yaml"
  - type: object
    properties:
      wasGeneratedBy:
        type: object
        required: [script, scriptVersion]
        properties:
          script: { type: string, format: iri }
          scriptVersion: { type: string }
          runId: { type: string }
          parameters: { type: object }
